name: axondeepsynth
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python>=3.12.1
  - numpy>=1.26.3
  - scipy>=1.12.0
  - ninja>=1.11.1
  - pip:
      - h5py>=3.10.0
      - imageio>=2.33.1
      - lazy-loader>=0.3
      - opencv-python>=4.8.1.78
      - packaging>=23.2
      - scikit-image>=0.22.0
      - tifffile>=2024.1.30
      - tqdm>=4.66.2
      - nnunetv2==2.2.1
      - hydra-core==1.3.2
